services:
  web:
    build:
      context: ./frontend
      args:
        VITE_CRISP_WEBSITE_ID: ${CRISP_WEBSITE_ID}
    container_name: beauty-code-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: beauty-code-backend
    expose:
      - "8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped