services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_CRISP_WEBSITE_ID: ${CRISP_WEBSITE_ID}
    container_name: beauty-code-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: beauty-code-backend
    expose:
      - "8080"
    environment:
      - AWS_REGION=eu-central-1
      - AWS_DYNAMODB_TABLE_NAME=BeautyCode
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
