services:
  backend-config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=prod,native,vault
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LDAP_URLS=${LDAP_URLS}
    restart: always