server:
  port: 8888

spring:
  application:
    name: backend-config-server
  profiles:
    active: dev,vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gchape/beauty-code.git
          search-paths: config
          default-label: feature/cloud
          refresh-rate: 0
          timeout: 8
          clone-on-start: true
          force-pull: true
        vault:
          host: ${VAULT_HOST:localhost}
          port: ${VAULT_PORT:8200}
          scheme: http
          backend: secret
          kv-version: 2

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.springframework.cloud.config: debug
---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: warn
    org.springframework.cloud.config: info
