spring:
  application:
    name: backend
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev

aws:
  region: eu-central-1
  dynamodb:
    table-name: BeautyCode

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: prod

aws:
  region: ${AWS_REGION}
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE_NAME}

logging:
  level:
    root: error