spring:
  cloud:
    aws:
      dynamodb:
        table-name: BeautyCode
  ldap:
    urls: ldap://localhost:8389
    embedded:
      port: 8389
      base-dn: dc=beautycode,dc=live
      ldif: classpath:ldap/schema.ldif
      validation:
        enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:beautycode}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      expiration-seconds: 21600

logging:
  level:
    root: debug