spring:
  cloud:
    aws:
      dynamodb:
        table-name: BeautyCode
  ldap:
    urls: ldap://localhost:8389
    embedded:
      port: 8389
      base-dn: dc=beautycode,dc=live
      ldif: classpath:ldap/schema.ldif
      validation:
        enabled: false
  security:
    jwt:
      expiration-seconds: 21600

logging:
  level:
    root: debug
